[theme]
primaryColor = "#000000"              # Replace with your chosen primary color
backgroundColor = "#E8E8E8"           # Replace with your chosen background color
secondaryBackgroundColor = "#ABA3EA"  # Replace with a secondary color
textColor = "#000000"                 # Replace with your chosen text color